### ISSUE TITLE
CLI option for output file instead of stdout

### ISSUE THREAD

**Issue by falkTX** [jpcima/faustpp#12]
While having faustpp output to stdout is fine for local usage, it is a problem for repeated/automated builds.
This is because using "x > y" syntax always creates a file even if the command that outputs to console fails, which can be a problem when faustpp is part of a build system pre-build step for example (the file is always created even if something fails).

Would be best for faustpp to be the one generating the output file, preferably only doing so if all early checks pass.

**Comment by jpcima** [comment]
It's implemented in 466f234.

**Comment by falkTX** [comment]
thanks!

**Comment by falkTX** [comment]
sadly the current implementation does not work as expected.
when the file has errors (for example the "identifier" name was not used/set), an empty output file is still generated.

**Comment by jpcima** [comment]
You're right, this is fixed now

**Comment by falkTX** [comment]
confirmed it works, thanks!

it is a bit weird that it deletes existing files if previous successful generation was done but new one fails, but not really a problem really, just a small oddity.
